-- Esquema reproducible de Retos Académicos.
-- Puede ejecutarse desde Supabase SQL Editor en un proyecto nuevo o existente.
create extension if not exists pgcrypto;

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  apellido text not null,
  rol text not null default 'estudiante' check (rol in ('estudiante', 'administrador')),
  estado text not null default 'activo' check (estado in ('activo', 'inactivo')),
  fecha_registro timestamptz not null default now()
);

create table if not exists public.asignaturas (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  icono_url text,
  estado text not null default 'activo' check (estado in ('activo', 'inactivo'))
);

create table if not exists public.niveles (
  id bigint generated by default as identity primary key,
  asignatura_id bigint not null references public.asignaturas(id) on delete cascade,
  numero_nivel integer not null check (numero_nivel > 0),
  nombre text not null,
  descripcion text,
  orden integer not null check (orden > 0),
  estado text not null default 'activo' check (estado in ('activo', 'inactivo')),
  unique (asignatura_id, numero_nivel),
  unique (asignatura_id, orden)
);

create table if not exists public.retos (
  id bigint generated by default as identity primary key,
  nivel_id bigint not null references public.niveles(id) on delete cascade,
  titulo text not null,
  descripcion text,
  tipo text not null check (tipo in ('quiz', 'verdadero_falso', 'trivia', 'desafio_reloj')),
  puntos_maximos integer not null default 10 check (puntos_maximos >= 0),
  orden integer not null check (orden > 0),
  estado text not null default 'activo' check (estado in ('activo', 'inactivo')),
  fecha_creacion timestamptz not null default now(),
  unique (nivel_id, orden)
);

create table if not exists public.contenidos_multimedia (
  id bigint generated by default as identity primary key,
  asignatura_id bigint not null references public.asignaturas(id) on delete cascade,
  nivel_id bigint references public.niveles(id) on delete cascade,
  tipo text not null check (tipo in ('video', 'imagen', 'texto', 'pdf')),
  titulo text not null,
  descripcion text,
  url_recurso text not null,
  orden integer not null check (orden > 0),
  estado text not null default 'activo' check (estado in ('activo', 'inactivo'))
);

create table if not exists public.reto_contenido (
  reto_id bigint not null references public.retos(id) on delete cascade,
  contenido_id bigint not null references public.contenidos_multimedia(id) on delete cascade,
  primary key (reto_id, contenido_id)
);

create table if not exists public.preguntas (
  id bigint generated by default as identity primary key,
  reto_id bigint not null references public.retos(id) on delete cascade,
  enunciado text not null,
  tipo text not null check (tipo in ('opcion_multiple', 'verdadero_falso', 'completar')),
  puntos integer not null default 10 check (puntos >= 0),
  orden integer not null check (orden > 0),
  respuesta_esperada text,
  estado text not null default 'activo' check (estado in ('activo', 'inactivo')),
  unique (reto_id, orden)
);

create table if not exists public.opciones_respuesta (
  id bigint generated by default as identity primary key,
  pregunta_id bigint not null references public.preguntas(id) on delete cascade,
  texto_opcion text not null,
  es_correcta boolean not null default false,
  orden integer not null check (orden > 0),
  unique (pregunta_id, orden)
);

create table if not exists public.intentos_reto (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  reto_id bigint not null references public.retos(id) on delete cascade,
  fecha_inicio timestamptz not null default now(),
  fecha_fin timestamptz,
  puntos_obtenidos integer not null default 0 check (puntos_obtenidos >= 0),
  porcentaje numeric(5,2) check (porcentaje between 0 and 100),
  estado text not null default 'en_progreso' check (estado in ('en_progreso', 'completado', 'abandonado'))
);

create table if not exists public.respuestas_usuario (
  id bigint generated by default as identity primary key,
  intento_id bigint not null references public.intentos_reto(id) on delete cascade,
  pregunta_id bigint not null references public.preguntas(id) on delete cascade,
  opcion_id bigint references public.opciones_respuesta(id) on delete set null,
  respuesta_texto text,
  es_correcta boolean,
  puntos_obtenidos integer not null default 0 check (puntos_obtenidos >= 0),
  unique (intento_id, pregunta_id)
);

create table if not exists public.insignias (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  icono_url text,
  criterio_obtencion text not null,
  puntos_requeridos integer check (puntos_requeridos >= 0),
  estado text not null default 'activo' check (estado in ('activo', 'inactivo'))
);

create table if not exists public.usuario_insignias (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  insignia_id bigint not null references public.insignias(id) on delete cascade,
  fecha_obtenida timestamptz not null default now(),
  unique (usuario_id, insignia_id)
);

create table if not exists public.progreso_global (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null unique references public.usuarios(id) on delete cascade,
  puntos_totales integer not null default 0 check (puntos_totales >= 0),
  nivel_actual integer not null default 1 check (nivel_actual > 0),
  porcentaje_progreso numeric(5,2) not null default 0 check (porcentaje_progreso between 0 and 100),
  racha_actual integer not null default 0 check (racha_actual >= 0),
  racha_maxima integer not null default 0 check (racha_maxima >= 0),
  fecha_ultimo_acceso timestamptz
);

create table if not exists public.ranking_global (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null unique references public.usuarios(id) on delete cascade,
  puntos_totales integer not null default 0 check (puntos_totales >= 0),
  posicion integer,
  fecha_actualizacion timestamptz not null default now()
);

create table if not exists public.desbloqueos_contenido (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  nivel_id bigint not null references public.niveles(id) on delete cascade,
  motivo text not null default 'reto_completado',
  fecha_desbloqueo timestamptz not null default now(),
  unique (usuario_id, nivel_id)
);

create table if not exists public.notificaciones (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  tipo text not null check (tipo in ('nuevo_reto', 'felicitacion_logro', 'alerta_racha_riesgo', 'recordatorio_estudio')),
  titulo text not null,
  mensaje text not null,
  fecha_programada timestamptz not null,
  fecha_envio timestamptz,
  leida boolean not null default false
);

-- Garantizan los objetivos usados por UPSERT incluso al adaptar una base existente.
create unique index if not exists progreso_global_usuario_uidx on public.progreso_global(usuario_id);
create unique index if not exists ranking_global_usuario_uidx on public.ranking_global(usuario_id);
create unique index if not exists usuario_insignias_usuario_insignia_uidx on public.usuario_insignias(usuario_id, insignia_id);
create unique index if not exists desbloqueos_usuario_nivel_uidx on public.desbloqueos_contenido(usuario_id, nivel_id);

create or replace function public.crear_perfil_usuario()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.usuarios (id, nombre, apellido)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'nombre'), ''), 'Estudiante'),
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'apellido'), ''), '')
  ) on conflict (id) do nothing;
  insert into public.progreso_global (usuario_id) values (new.id) on conflict (usuario_id) do nothing;
  insert into public.ranking_global (usuario_id) values (new.id) on conflict (usuario_id) do nothing;
  return new;
end;
$$;

drop trigger if exists al_crear_usuario on auth.users;
create trigger al_crear_usuario after insert on auth.users
for each row execute function public.crear_perfil_usuario();

create or replace function public.es_administrador()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.usuarios
    where id = auth.uid() and rol = 'administrador' and estado = 'activo'
  );
$$;

-- La finalización es una sola transacción. Las respuestas locales se recalculan
-- contra preguntas y opciones guardadas; los parámetros externos solo se usan
-- para trivias sin preguntas locales y siempre se limitan al máximo del reto.
create or replace function public.finalizar_reto(
  p_intento_id bigint,
  p_puntos_externos integer default 0,
  p_aciertos_externos integer default 0,
  p_total_externos integer default 0
) returns jsonb
language plpgsql
security definer set search_path = public
as $$
declare
  v_intento public.intentos_reto%rowtype;
  v_reto public.retos%rowtype;
  v_progreso public.progreso_global%rowtype;
  v_total integer := 0;
  v_aciertos integer := 0;
  v_puntos integer := 0;
  v_porcentaje numeric(5,2) := 0;
  v_aprobado boolean := false;
  v_aprobado_antes boolean := false;
  v_primera_aprobacion boolean := false;
  v_puntos_otorgados integer := 0;
  v_puntos_totales integer := 0;
  v_nivel_actual integer := 1;
  v_porcentaje_global numeric(5,2) := 0;
  v_racha integer := 1;
  v_siguiente_nivel public.niveles%rowtype;
  v_nivel_desbloqueado text := null;
  v_insignias jsonb := '[]'::jsonb;
  v_insertadas integer := 0;
begin
  select * into v_intento from public.intentos_reto
  where id = p_intento_id and usuario_id = auth.uid() for update;
  if not found then raise exception 'Intento no encontrado o sin autorización'; end if;
  if v_intento.estado <> 'en_progreso' then raise exception 'El intento ya fue finalizado'; end if;

  select * into v_reto from public.retos where id = v_intento.reto_id;

  select count(*),
         count(*) filter (where
           (p.tipo = 'completar' and lower(trim(coalesce(ru.respuesta_texto, ''))) = lower(trim(coalesce(p.respuesta_esperada, '')))
             and trim(coalesce(p.respuesta_esperada, '')) <> '')
           or (p.tipo <> 'completar' and coalesce(op.es_correcta, false))
         ),
         coalesce(sum(case when
           (p.tipo = 'completar' and lower(trim(coalesce(ru.respuesta_texto, ''))) = lower(trim(coalesce(p.respuesta_esperada, '')))
             and trim(coalesce(p.respuesta_esperada, '')) <> '')
           or (p.tipo <> 'completar' and coalesce(op.es_correcta, false))
           then p.puntos else 0 end), 0)
  into v_total, v_aciertos, v_puntos
  from public.preguntas p
  left join public.respuestas_usuario ru on ru.pregunta_id = p.id and ru.intento_id = v_intento.id
  left join public.opciones_respuesta op on op.id = ru.opcion_id and op.pregunta_id = p.id
  where p.reto_id = v_reto.id and p.estado = 'activo';

  if v_total = 0 and v_reto.tipo = 'trivia' then
    v_total := greatest(p_total_externos, 0);
    v_aciertos := least(greatest(p_aciertos_externos, 0), v_total);
    v_puntos := least(greatest(p_puntos_externos, 0), v_reto.puntos_maximos);
  else
    v_puntos := least(v_puntos, v_reto.puntos_maximos);
  end if;

  if v_total > 0 then v_porcentaje := round((v_aciertos::numeric / v_total::numeric) * 100, 2); end if;
  v_aprobado := v_porcentaje >= 60;
  select exists (
    select 1 from public.intentos_reto
    where usuario_id = auth.uid() and reto_id = v_reto.id and id <> v_intento.id
      and estado = 'completado' and porcentaje >= 60
  ) into v_aprobado_antes;
  v_primera_aprobacion := v_aprobado and not v_aprobado_antes;

  update public.intentos_reto set
    fecha_fin = now(), puntos_obtenidos = v_puntos,
    porcentaje = v_porcentaje, estado = 'completado'
  where id = v_intento.id;

  select * into v_progreso from public.progreso_global
  where usuario_id = auth.uid() for update;
  if not found then
    insert into public.progreso_global (usuario_id) values (auth.uid()) returning * into v_progreso;
  end if;

  if v_progreso.fecha_ultimo_acceso is null then v_racha := 1;
  elsif current_date - v_progreso.fecha_ultimo_acceso::date = 0 then v_racha := greatest(v_progreso.racha_actual, 1);
  elsif current_date - v_progreso.fecha_ultimo_acceso::date = 1 then v_racha := v_progreso.racha_actual + 1;
  else v_racha := 1;
  end if;

  v_puntos_otorgados := case when v_primera_aprobacion then v_puntos else 0 end;
  v_puntos_totales := v_progreso.puntos_totales + v_puntos_otorgados;
  v_nivel_actual := floor(v_puntos_totales / 100.0)::integer + 1;
  select coalesce(round(
    count(distinct i.reto_id) filter (where i.estado = 'completado' and i.porcentaje >= 60)::numeric
      / nullif((select count(*) from public.retos where estado = 'activo'), 0)::numeric * 100, 2
  ), 0) into v_porcentaje_global
  from public.intentos_reto i
  join public.retos r on r.id = i.reto_id
  where i.usuario_id = auth.uid() and r.estado = 'activo';

  update public.progreso_global set
    puntos_totales = v_puntos_totales,
    nivel_actual = v_nivel_actual,
    porcentaje_progreso = v_porcentaje_global,
    racha_actual = v_racha,
    racha_maxima = greatest(racha_maxima, v_racha),
    fecha_ultimo_acceso = now()
  where usuario_id = auth.uid();

  insert into public.ranking_global (usuario_id, puntos_totales, fecha_actualizacion)
  values (auth.uid(), v_puntos_totales, now())
  on conflict (usuario_id) do update set
    puntos_totales = excluded.puntos_totales,
    fecha_actualizacion = excluded.fecha_actualizacion;

  if v_primera_aprobacion then
    select coalesce(jsonb_agg(to_jsonb(i)), '[]'::jsonb) into v_insignias
    from public.insignias i
    where i.estado = 'activo' and i.puntos_requeridos is not null
      and i.puntos_requeridos <= v_puntos_totales
      and not exists (
        select 1 from public.usuario_insignias ui
        where ui.usuario_id = auth.uid() and ui.insignia_id = i.id
      );
    insert into public.usuario_insignias (usuario_id, insignia_id)
    select auth.uid(), i.id from public.insignias i
    where i.estado = 'activo' and i.puntos_requeridos is not null
      and i.puntos_requeridos <= v_puntos_totales
    on conflict (usuario_id, insignia_id) do nothing;

    if not exists (
      select 1 from public.retos r
      where r.nivel_id = v_reto.nivel_id and r.estado = 'activo'
        and not exists (
          select 1 from public.intentos_reto i
          where i.usuario_id = auth.uid() and i.reto_id = r.id
            and i.estado = 'completado' and i.porcentaje >= 60
        )
    ) then
      select n.* into v_siguiente_nivel
      from public.niveles actual
      join public.niveles n on n.asignatura_id = actual.asignatura_id
        and n.orden > actual.orden and n.estado = 'activo'
      where actual.id = v_reto.nivel_id order by n.orden limit 1;
      if found then
        insert into public.desbloqueos_contenido (usuario_id, nivel_id, motivo)
        values (auth.uid(), v_siguiente_nivel.id, 'reto_completado')
        on conflict (usuario_id, nivel_id) do nothing;
        get diagnostics v_insertadas = row_count;
        if v_insertadas > 0 then v_nivel_desbloqueado := v_siguiente_nivel.nombre; end if;
      end if;
    end if;
  end if;

  return jsonb_build_object(
    'aprobado', v_aprobado,
    'puntosOtorgados', v_puntos_otorgados,
    'puntosTotales', v_puntos_totales,
    'porcentajeGeneral', v_porcentaje_global,
    'nivelActual', v_nivel_actual,
    'rachaActual', v_racha,
    'insigniasNuevas', v_insignias,
    'nivelDesbloqueado', v_nivel_desbloqueado
  );
end;
$$;

grant execute on function public.finalizar_reto(bigint, integer, integer, integer) to authenticated;
grant execute on function public.es_administrador() to authenticated;

create or replace function public.corregir_puntos_usuario(p_usuario_id uuid, p_puntos integer)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.es_administrador() then raise exception 'Acceso denegado'; end if;
  if p_puntos < 0 then raise exception 'Los puntos no pueden ser negativos'; end if;
  update public.progreso_global set
    puntos_totales = p_puntos,
    nivel_actual = floor(p_puntos / 100.0)::integer + 1
  where usuario_id = p_usuario_id;
  update public.ranking_global set
    puntos_totales = p_puntos,
    fecha_actualizacion = now()
  where usuario_id = p_usuario_id;
end;
$$;
grant execute on function public.corregir_puntos_usuario(uuid, integer) to authenticated;

-- RLS: los catálogos activos son de lectura; las mutaciones de catálogo son administrativas.
do $$ declare t text; begin
  foreach t in array array[
    'usuarios','asignaturas','niveles','retos','contenidos_multimedia','reto_contenido',
    'preguntas','opciones_respuesta','intentos_reto','respuestas_usuario','insignias',
    'usuario_insignias','progreso_global','ranking_global','desbloqueos_contenido','notificaciones'
  ] loop execute format('alter table public.%I enable row level security', t); end loop;
end $$;

create policy "usuarios leen perfil propio" on public.usuarios for select to authenticated using (id = auth.uid() or public.es_administrador());
create policy "perfiles activos visibles" on public.usuarios for select to authenticated using (estado = 'activo');
create policy "administradores gestionan usuarios" on public.usuarios for all to authenticated using (public.es_administrador()) with check (public.es_administrador());

create policy "catalogo asignaturas visible" on public.asignaturas for select to authenticated using (estado = 'activo' or public.es_administrador());
create policy "admin asignaturas" on public.asignaturas for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "catalogo niveles visible" on public.niveles for select to authenticated using (estado = 'activo' or public.es_administrador());
create policy "admin niveles" on public.niveles for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "catalogo retos visible" on public.retos for select to authenticated using (estado = 'activo' or public.es_administrador());
create policy "admin retos" on public.retos for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "catalogo contenidos visible" on public.contenidos_multimedia for select to authenticated using (estado = 'activo' or public.es_administrador());
create policy "admin contenidos" on public.contenidos_multimedia for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "vinculos contenido visibles" on public.reto_contenido for select to authenticated using (true);
create policy "admin vinculos contenido" on public.reto_contenido for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "catalogo preguntas visible" on public.preguntas for select to authenticated using (estado = 'activo' or public.es_administrador());
create policy "admin preguntas" on public.preguntas for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "opciones visibles" on public.opciones_respuesta for select to authenticated using (true);
create policy "admin opciones" on public.opciones_respuesta for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "insignias visibles" on public.insignias for select to authenticated using (estado = 'activo' or public.es_administrador());
create policy "admin insignias" on public.insignias for all to authenticated using (public.es_administrador()) with check (public.es_administrador());

create policy "intentos propios" on public.intentos_reto for select to authenticated using (usuario_id = auth.uid() or public.es_administrador());
create policy "crear intentos propios" on public.intentos_reto for insert to authenticated with check (
  usuario_id = auth.uid() and estado = 'en_progreso' and fecha_fin is null
  and puntos_obtenidos = 0 and porcentaje is null
);
create policy "respuestas propias" on public.respuestas_usuario for select to authenticated using (exists (select 1 from public.intentos_reto i where i.id = intento_id and (i.usuario_id = auth.uid() or public.es_administrador())));
create policy "crear respuestas propias" on public.respuestas_usuario for insert to authenticated with check (exists (select 1 from public.intentos_reto i where i.id = intento_id and i.usuario_id = auth.uid()));
create policy "insignias propias" on public.usuario_insignias for select to authenticated using (usuario_id = auth.uid() or public.es_administrador());
create policy "progreso propio" on public.progreso_global for select to authenticated using (usuario_id = auth.uid() or public.es_administrador());
create policy "admin actualiza progreso" on public.progreso_global for update to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "ranking visible" on public.ranking_global for select to authenticated using (true);
create policy "admin actualiza ranking" on public.ranking_global for update to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "desbloqueos propios" on public.desbloqueos_contenido for select to authenticated using (usuario_id = auth.uid() or public.es_administrador());
create policy "notificaciones propias" on public.notificaciones for select to authenticated using (usuario_id = auth.uid() or public.es_administrador());
create policy "registrar notificacion propia" on public.notificaciones for insert to authenticated with check (usuario_id = auth.uid());

-- El panel administrativo requiere acceso total a registros operativos.
create policy "admin intentos" on public.intentos_reto for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "admin respuestas" on public.respuestas_usuario for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "admin usuario insignias" on public.usuario_insignias for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "admin desbloqueos" on public.desbloqueos_contenido for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
create policy "admin notificaciones" on public.notificaciones for all to authenticated using (public.es_administrador()) with check (public.es_administrador());
